test_that("initialisation works", {
  game_state <- InitialiseGameState(seed = 1, starting_player = 1)
  expect_equal(game_state$deck %>% length(), 30)
  expect_equal(game_state$player1$hand %>% length(), 3)
  expect_equal(game_state$player2$hand %>% length(), 3)
  expect_equal(game_state$board %>% length(), 4)
  expect_equal(game_state$player1$stack %>% length(), 0)
  expect_equal(game_state$player2$stack %>% length(), 0)
  expect_equal(game_state$turn, 1)
})
