test_that("Comparing two players work", {
  one_comp = RunOneGame(starting_player = 1, DecisionFunction1 = RandomDecision)
  expect_type(one_comp, "list")
  expect_equal(nrow(one_comp), 1)
  expect_equal(ncol(one_comp), 3)
  comp2players_many_games = RunManyGamesparallel(DecisionFunction1 = RandomDecision, n_procs = 2)
  expect_type(comp2players_many_games, "list")
  expect_equal(nrow(comp2players_many_games), 28)
  expect_equal(ncol(comp2players_many_games), 3)
  one_comp = RunOneGame(starting_player = 1, DecisionFunction1 = RandomDecision, detailed_output = T)
  expect_type(one_comp, "list")
  expect_equal(nrow(one_comp), 1)
  expect_gt(ncol(one_comp), 3)
  comp2players_many_games = RunManyGamesparallel(DecisionFunction1 = RandomDecision, n_procs = 2, detailed_output = T)
  expect_type(comp2players_many_games, "list")
  expect_equal(nrow(comp2players_many_games), 28)
  expect_gt(ncol(comp2players_many_games), 3)
  
  one_comp = CompareTwoPlayersOneDeck(DecisionFunction1 = RandomDecision)
  expect_equal(nrow(one_comp), 2)
  comp2players_many_games = RunManyPairedGamesparallel(DecisionFunctions = c(RandomDecision, RandomDecision), n_procs = 2)
  expect_equal(nrow(comp2players_many_games), 42)
})
